galaxy_info:
  author: codenamenuke
  description: MySQL role for setting up MySQL DB and user

  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 18.04

  galaxy_tags:
    - wordpress
    - ubuntu
