galaxy_info:
  author: codenamenuke
  description: PHP Role installs the base PHP dependencies for WP

  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 18.04

  galaxy_tags:
    - wordpress
    - ubuntu
