galaxy_info:
  author: codenamenuke
  description: Server role installs all the required dependencies

  license: license (MIT)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 18.04

  galaxy_tags:
    - wordpress
    - ubuntu
